project_name: nomad-driver-tart
builds:
  - id: nomad-driver-tart
    main: ./main.go
    goos:
      - darwin
    goarch:
      - arm64
    ldflags: -s -w
archives:
  - id: nomad-driver-tart
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
release:
  github:
    owner: brianmichel
    name: nomad-driver-tart
