version: 2
project_name: nomad-driver-tart
builds:
  - id: nomad-driver-tart
    main: ./main.go
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags: -s -w
    hooks:
      post:
        - sh codesign.sh "Developer ID Application" dist

archives:
  - id: nomad-driver-tart
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

signs:
  - cmd: cosign
    stdin: "{{ .Env.COSIGN_PWD }}"
    args:
      - "sign-blob"
      - "--key=cosign.key"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: all

release:
  github:
    owner: brianmichel
    name: nomad-driver-tart

snapshot:
  version_template: "{{ .ProjectName }}-SNAPSHOT-{{ .ShortCommit }}"
