[tools]
go = "1.24.4"

[tasks]
# Build the Nomad Tart driver plugin
build = "go build -o dist/nomad-driver-tart main.go"

# Clean up build artifacts
clean = "rm -f dist/nomad-driver-tart"

# Format code
fmt = "go fmt ./..."

# Vet code
vet = "go vet ./..."

# Run tests
test = "go test ./... -v"

# Run all checks and build (equivalent to 'all' target)
all = "mise run fmt && mise run vet && mise run build"

# Development workflow - format, vet, test, and build
dev = "mise run fmt && mise run vet && mise run test && mise run build"

# Install dependencies
deps = "go mod download"

# Update dependencies
deps-update = "go get -u ./... && go mod tidy"

# Show build info
info = "echo 'Building Nomad Tart driver plugin...' && mise run build && echo 'Build complete: dist/nomad-driver-tart'"
