name: CI

on:
  push:
    branches: ["main"]
    tags:
      - 'v*'
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run gofmt
        run: gofmt -w $(git ls-files '*.go')
      - name: Run go vet
        run: go vet ./...
      - name: Build darwin arm64 binary
        env:
          GOOS: darwin
          GOARCH: arm64
        run: go build -o nomad-driver-tart-${GOOS}-${GOARCH} main.go
      - uses: actions/upload-artifact@v3
        with:
          name: nomad-driver-tart-${{ github.sha }}
          path: nomad-driver-tart-darwin-arm64

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Build darwin arm64 binary
        env:
          GOOS: darwin
          GOARCH: arm64
        run: go build -o nomad-driver-tart-${GOOS}-${GOARCH} main.go
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "nomad-driver-tart-darwin-arm64"
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
