name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to build a snapshot from'
        required: false
        default: main

jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
      - name: Install Signing Key
        run: |
          echo "${{ secrets.COSIGN_KEY }}" > cosign.base64.key
          base64 -d -i cosign.base64.key -o cosign.key
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run GoReleaser (full release)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: goreleaser/goreleaser-action@v6.3.0
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PWD: ${{ secrets.COSIGN_PASSWORD }}
      - name: Run GoReleaser (snapshot)
        if: github.event_name == 'workflow_dispatch'
        uses: goreleaser/goreleaser-action@v6.3.0
        with:
          version: latest
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PWD: ${{ secrets.COSIGN_PASSWORD }}
      - name: Upload snapshot artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-artifacts-${{ github.run_id }}
          path: dist/
